export declare function getPRESSED_STATE_SET(): void;
export declare function getHOVERED_FOCUSED_STATE_SET(): void;
export declare function getFOCUSED_STATE_SET(): void;
export declare function getHOVERED_STATE_SET(): void;
export declare function getSELECTED_PRESSED_STATE_SET(): void;
export declare function getSELECTED_HOVERED_FOCUSED_STATE_SET(): void;
export declare function getSELECTED_FOCUSED_STATE_SET(): void;
export declare function getSELECTED_HOVERED_STATE_SET(): void;
export declare function getSELECTED_STATE_SET(): void;
export declare function getRippleColorStateList(color: number): globalAndroid.content.res.ColorStateList;
export declare function getEnabledColorStateList(color: number, variant: string): globalAndroid.content.res.ColorStateList;
